{% set version = "2022.06.0" %}

package:
  name: uxarray
  version: {{ version }}

source:
  url: https://github.com/UXARRAY/uxarray/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: e4afaf5a1383c1a3be00fd4870877a1b1b6e4f893823318146a60138cbc38b38

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - xarray

test:
  source_files:
    - test
  requires:
    - dask
    - netcdf4
    - pytest
  imports:
    - uxarray
  commands:
    - pytest test

about:
  home: https://github.com/UXARRAY/uxarray
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Uxarray is a library of xarray based functions for visualizing unstructured grid datasets'

extra:
  recipe-maintainers:
    - paullric
    - erogluorhan
    - anissa111
    - michaelavs
    - rajeeja
    - chengzhuzhang
    - marodrig
