{% set name = "uxarray" %}
{% set version = "2025.05.2" %}
{% set python_min = "3.10" %}



package:
  name: uxarray
  version: {{ version }}

source:
  url: https://github.com/UXARRAY/uxarray/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: 661c3f980cb006ab1d37a900fa4d4d87b430c9df34a908d76f06e440f78a676e

build:
  number: 0

  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - antimeridian
    - cartopy
    - dask
    - datashader
    - geoviews
    - healpix
    - holoviews
    - hvplot
    - matplotlib-base
    - matplotlib-inline
    - netcdf4
    - numba
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-learn
    - scipy >=0.16
    - shapely
    - spatialpandas
    - xarray
    - polars

test:
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - uxarray

about:
  home: https://github.com/UXARRAY/uxarray
  description: |
    Uxarray aims to address the geoscience community need for tools that enable standard data analysis techniques to operate directly on unstructured grid data.
    Uxarray will provide Xarray styled functions to better read in and use unstructured grid datasets that follow standard conventions, including UGRID, SCRIP,
    Exodus and shapefile formats. This effort is a result of the collaboration between Project Raijin
    (NCAR and Pennsylvania State University) and the SEATS Project (Argonne National Laboratory, UC Davis, and Lawrence Livermore National Laboratory).
    The Uxarray team welcomes other community members to become part of this collaboration at any level of contribution.

  license: Apache-2.0
  license_file: LICENSE
  summary: Xarray extension for unstructured climate and global weather data analysis and visualization

extra:
  recipe-maintainers:
    - xylar
    - paullric
    - erogluorhan
    - anissa111
    - rajeeja
    - chengzhuzhang
    - philipc2
