{% set version = "2024.01.0" %}

package:
  name: uxarray
  version: {{ version }}

source:
  url: https://github.com/UXARRAY/uxarray/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: 57344d85758f132cf9cf310690e6bc546aa329edadb07c03df65f9cd3a3d4b44

build:
  number: 0

  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - cartopy
    - dask
    - datashader
    - holoviews
    - matplotlib-base
    - netcdf4
    - numba
    - numpy
    - pandas
    - scikit-learn
    - scipy >=0.16
    - xarray

test:
  requires:
    - pytest
  imports:
    - uxarray

about:
  home: https://github.com/UXARRAY/uxarray
  description: |
    Uxarray aims to address the geoscience community need for tools that enable standard data analysis techniques to operate directly on unstructured grid data.
    Uxarray will provide Xarray styled functions to better read in and use unstructured grid datasets that follow standard conventions, including UGRID, SCRIP,
    Exodus and shapefile formats. This effort is a result of the collaboration between Project Raijin
    (NCAR and Pennsylvania State University) and the SEATS Project (Argonne National Laboratory, UC Davis, and Lawrence Livermore National Laboratory).
    The Uxarray team welcomes other community members to become part of this collaboration at any level of contribution.

  license: Apache-2.0
  license_file: LICENSE
  summary: Uxarray is a library of xarray based functions for visualizing unstructured grid datasets

extra:
  recipe-maintainers:
    - paullric
    - erogluorhan
    - anissa111
    - rajeeja
    - chengzhuzhang
    - philipc2
