{% set name = "uxarray" %}
{% set version = "2024.11.1" %}


package:
  name: uxarray
  version: {{ version }}

source:
  url: https://github.com/UXARRAY/uxarray/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: c71ab33e6eb88909f825fee5a8c696aea19462c700b74ca69159507a5ad0e22b

build:
  number: 0

  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools-scm
  run:
    - antimeridian
    - cartopy
    - dask
    - datashader
    - geoviews
    - holoviews
    - hvplot
    - matplotlib-base
    - matplotlib-inline
    - netcdf4
    - numba
    - numpy
    - pandas
    - python >=3.9
    - scikit-learn
    - scipy >=0.16
    - shapely
    - spatialpandas
    - xarray

test:
  requires:
    - pytest
  imports:
    - uxarray

about:
  home: https://github.com/UXARRAY/uxarray
  description: |
    Uxarray aims to address the geoscience community need for tools that enable standard data analysis techniques to operate directly on unstructured grid data.
    Uxarray will provide Xarray styled functions to better read in and use unstructured grid datasets that follow standard conventions, including UGRID, SCRIP,
    Exodus and shapefile formats. This effort is a result of the collaboration between Project Raijin
    (NCAR and Pennsylvania State University) and the SEATS Project (Argonne National Laboratory, UC Davis, and Lawrence Livermore National Laboratory).
    The Uxarray team welcomes other community members to become part of this collaboration at any level of contribution.

  license: Apache-2.0
  license_file: LICENSE
  summary: Xarray extension for unstructured climate and global weather data analysis and visualization

extra:
  recipe-maintainers:
    - paullric
    - erogluorhan
    - anissa111
    - rajeeja
    - chengzhuzhang
    - philipc2
